export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_LOGOUT = 'USER_LOGOUT';

export const LOAD_COLLECTIONS = 'LOAD_COLLECTIONS';
export const LOAD_COLLECTIONS_CHART_DATA = 'LOAD_COLLECTIONS_CHART_DATA';
export const LOAD_COLLECTIONS_AND_VALUES = 'LOAD_COLLECTIONS_AND_VALUES';
export const LOAD_COLLECTIONS_AND_VALUES_FOR_MONTH = 'LOAD_COLLECTIONS_AND_VALUES_FOR_MONTH';
export const REMOVE_COLLECTION = 'REMOVE_COLLECTION';

export const LOAD_EXPENSES = 'LOAD_EXPENSES';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';

export const LOAD_INCOMES = 'LOAD_INCOMES';
export const REMOVE_INCOME = 'REMOVE_INCOME';